const tags_family = [
    { id: 'pj', name: '配将' },
    { id: 'kh', name: '开荒' },
    { id: 'mxqz', name: '萌新求助' },
    { id: 'zfa', name: '战法' },
    { id: 'zf', name: '征服' },
    { id: 'gj', name: '割据' },
    { id: 'ss', name: '试师' },
    { id: 'oh', name: '欧皇' },
    { id: 'gc', name: '攻城' },
    { id: 'pl', name: '铺路' },
    { id: 'ts', name: '太守' },
    { id: 'bw', name: '宝物' },
    { id: 'hx', name: '画像' },
    { id: 'ck', name: '抽卡' },
    { id: 'nz', name: '内政' },
    { id: 'zysj', name: '簪缨世家' },
    { id: 'sxmd', name: '书香门第' },
    { id: 'lyck', name: '洛阳常客' },
    { id: 'qmsz', name: '奇谋善战' },
    { id: 'wfbd', name: '万夫不当' },
    { id: 'nysb', name: '能言善辩' },
    { id: 'yjjg', name: '远交近攻' },
    { id: 'hzlh', name: '合纵连横' },
    { id: 'qlzs', name: '千里斩首' },
    { id: 'ycww', name: '运筹帷幄' },
    { id: 'csjj', name: '常胜将军' },
    { id: 'hfhy', name: '呼风唤雨' },
    { id: 'bzbs', name: '百战百胜' },
    { id: 'lxbc', name: '连下百城' },
    { id: 'yrql', name: '一日千里' },
    { id: 'cjcr', name: '冲坚摧锐' },
    { id: 'mwyc', name: '谋无遗策' },
    { id: 'brxh', name: '辩若悬河' },
    { id: 'fclz', name: '凤雏麟子' },
    { id: 'bdjg', name: '兵多将广' },
    { id: 'sxpm', name: '所向披靡' },
];

export default { tags_family };

